### ISSUE TITLE
OKR table overview of ideas using yaml frontmatter

### ISSUE THREAD

**Issue by oskarth** [status-im/swarms#213]
Re-create: https://docs.google.com/spreadsheets/d/1BhWKyjkpxhavkqtk9VYB3EHNDIzQtUlkwlg7_lQNAws/edit#gid=0 view for OKRs https://ideas.status.im (Core ones only)

![image](https://user-images.githubusercontent.com/1552237/39282804-8ed181ee-493d-11e8-9647-0d45ee0ec472.png)

Specific implementation open. The end result should reflect which swarms are currently working towards OKRs.

Suggestion: use `okr` field in ideas and create data index file like `okrs.yaml`(similar to `contributors.yaml` to map between swarms and okrs.

<blockquote><img src="https://lh3.googleusercontent.com/7xzB62VWyYtIQPkJLj5ZzXEc3Mnfy2nKMCeYHdYNjdI3k2wTZHAA2zcYZXi11e0BfJvcUg=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/spreadsheets/d/1BhWKyjkpxhavkqtk9VYB3EHNDIzQtUlkwlg7_lQNAws/edit?usp=embed_facebook">Q2 Status OKRs</a></strong></div><div># core

[ O] P, ID, Objective,[ KR] P, Key Result, Swarm# 1, Swarm# 2, Swarm# 3, Swarm# 4, Swarm# 5, Mid-Q Score, Final Score, Notes
 P0, 1. 1, Messaging is reliable, P0, Send/ delivered ratio> 99%,# 92,# 99, 91
 P0, 1. 2, Messaging is reliable, P0,> 95% of 20+ people surveyed trust Status for me...</div></blockquote>
<blockquote><div>Status - Ideas</div><div><strong><a href="http://ideas.status.im/">Home</a></strong></div><div>Swarm Home. New, completed and in-progress features for Status.</div></blockquote>

**Comment by oskarth** [comment]
@andytudhope I think this one is pretty exciting for people who are into Status process/goals and static site stuff, it's fairly free form

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x2e3f9d30523cc2d74610177b9d7136f8baaa6e075a434c48e3082011a1e13dfa](https://etherscan.io/tx/0x2e3f9d30523cc2d74610177b9d7136f8baaa6e075a434c48e3082011a1e13dfa)

**Comment by alexkohler** [comment]
@oskarth - I'm a little unclear - Is the intent to create an entirely new OKR page (in addition to Ideas and People) on https://ideas.status.im/ or integrate this data into the existing ideas page? (https://ideas.status.im/all)

**Comment by oskarth** [comment]
@alexkohler A new page seems reasonable to me :)

**Comment by debragail** [comment]
Also still think think recreating the wheel doesn't make a lot of sense.  you can use something like this with Jira:

https://swarmos.com/

**Comment by debragail** [comment]
Also I brought it up in #general but uses Jekyll and static web pages isn't going to work for what you're trying to accomplish.  It's currently configured to work as a blog and this should be a dynamic site.

**Comment by oskarth** [comment]
No opinion on coloring, whatever seems reasonable for now :)

Using a static site is no technical blocker for this.

**Comment by debragail** [comment]
@oskarth what does the P stand for or [O] P and [KR] P and P0, P1, etc?

**Comment by debragail** [comment]
@oskarth what does the pink mean vs the green?

**Comment by oskarth** [comment]
@debragail pink is if the swarm is in draft/limbo mode, green if it is active :)

**Comment by debragail** [comment]
@oskarth should OKRs be their own md file?  If so should they be 3 digits as well?  so far it's 1.1 decimal format for the ID.

**Comment by oskarth** [comment]
Not sure - I was thinking it could be a `18Q2-core-okr.yml` file with a format like https://github.com/status-im/ideas/blob/master/_data/statuses.yaml to capture the raw data, but maybe there are better ways to capture it. Whatever makes sense and solves the problem :)

**Comment by debragail** [comment]
for reference:

https://github.com/ethereum/EIPs

**Comment by debragail** [comment]
@oskarth so I made the table but here's the problem i'm running into:

1.  I still had the null object sort problem when using jekyll serve ... not sure how to get around that locally.
2.  Since the OKR table has it's own id, and two types of data Objective and Key Result; each with it's own priority, i don't think we can encapsulate that data an idea .md file.  Because it's not a one to one mapping.  For example #99 relates to 1.1, 1.2, and 1.3.  I can't think of an elegant way to do this.
3.  If i create a new data type 1.1-messaging-is-reliable.md which would work, I don't know how to get the table to pull from a new OKRs directory.  When i read the jekyll docs it seems that you replaced posts with ideas and that jekyll has a specific directory structure.  I'm not sure how i feel about that .md file living in the ideas folder but maybe thats how it should be?

I'll push what i've worked on so far so you can see where i'm headed with this.

**Comment by debragail** [comment]
https://github.com/debragail/ideas/tree/%23213-new-OKR-table
