### ISSUE TITLE
ideas labeled differently in html files

### ISSUE THREAD

**Issue by debragail** [status-im/swarms#236]
td class is labeled differently for ideas in ideas table and people table:

**Current:**

../_includes/ideastable.html
`` <td `class="id"><a` `href="{{page.url|relative_url}}">{{page.id|xml_escape}}</a></td>`

../_includes/peopletable.html
`` <td `class="idea"><a` `href="{{page.url|relative_url}}">{{page.id|xml_escape}}</a></td>`

**Expected:**

../_includes/ideastable.html
`` <td `class="idea"><a` `href="{{page.url|relative_url}}">{{page.id|xml_escape}}</a></td>`

../_includes/peopletable.html
`` <td `class="idea"><a` `href="{{page.url|relative_url}}">{{page.id|xml_escape}}</a></td>`

Maybe change page.id to page.idea ?

**Comment by oskarth** [comment]
Closing to reflect current issue state. We might revisit this later but not a prio for the forseeable future. Likely to be integrated with new docs site / DAO etc.
