### ISSUE TITLE
Missing budget for all active swarms

### ISSUE THREAD

**Issue by oskarth** [status-im/swarms#352]
They should have rough budget.

SNT Utility
- [ ] 316-core-network-incentivization (research)
- [ ] 313-sticker-market (research)
- [ ] 314-tribute-to-talk (research)
- [ ] 317-dapp-store (research)
- [ ] TODO: Teller Network

Essential
- [ ] 315-core-improvements (research)
- [ ] 311-protocol (research)
- [ ] TODO: DAO
- [ ] 312-janitors (research)

Teams (fallback for responsibility)
- [ ] 310-core (research)
- [ ] 306-core-browser (research)
- [ ] 304-core-chat (research)
- [ ] 318-desktop (research)
- [ ] 319-wallet (research)
- [ ] 320-keycard (research)

**Comment by jeluard** [comment]
@oskarth Can you detail what is expected regarding budget?

**Comment by oskarth** [comment]
@jeluard should've clarified - this one is likely going to be for @naghdy (and other janitors?) initially.

Details TBD - I think the main thing that might be needed is % time spent per swarm, but we'll see how we deal with this going forward. No rush with it now.

**Comment by naghdy** [comment]
Have created this: https://docs.google.com/spreadsheets/d/1P4zc6ODJGAY_ErnTHMyHvOSq6NHXnp9VxF3wP6yFPhQ/edit#gid=0. If people can please put in the average # of hours spent per week per swarm (something that can done during the weekly syncs), then we can figure out total budget for swarms.

**Comment by naghdy** [comment]
I'll also be able to mostly figure it out from Pivotal Tracker based on points, but until all work goes through there (and points automatically learn the respective value), we will have to do it manually.

**Comment by oskarth** [comment]
Closing as this is being tracked elsewhere.
