### ISSUE TITLE
Research completion sanity check

### ISSUE THREAD

**Issue by oskarth** [status-im/swarms#354]
A lot of swarms set 21/1 (before Christmas) as their research deadline. From this we expect some concrete output. This issue will track this.

Acceptance criteria per swarm:
- updated swarm with research findings and rough plan for specification
- sanity checked by janitors

SNT Utility
- [x] 316-core-network-incentivization (research)
- [x] 313-sticker-market (research)
- [x] 314-tribute-to-talk (research)
- [ ] 317-dapp-store (research)
- [ ] TODO: Teller Network

Essential
- [x] 315-core-improvements (research)
- [ ] 311-protocol (research)
- [ ] TODO: DAO
- [ ] 312-janitors (research)

Teams (fallback for responsibility)
- [x] 310-core (research)
- [x] 306-core-browser (research)
- [x] 304-core-chat (research)
- [ ] 318-desktop (research)
- [x] 319-wallet (research)
- [ ] 320-keycard (implementation)

**Comment by jeluard** [comment]
`313-sticker-market` research phase has been extended to 28/12 and `317-dapp-store` to 04/01.

**Comment by jeluard** [comment]
@oskarth Research for both sticker market and browser have been completed.

**Comment by rachelhamlin** [comment]
Research also complete for TtT, core chat, core wallet. Added relevant links to wallet swarm writeup and updated chat writeup. ✔

**Comment by guylouis** [comment]
Keycard is in implementation phase now. I updated the Swarm with some update on the specification phase, and where we're at in the implementation phase.

**Comment by mandrigin** [comment]
@oskarth I’ve updated the swarm docs. TL;DR Improvements - research complete, Incentivization - research WIP

**Comment by oskarth** [comment]
Closing as no longer relevant for these swarms.
